"""Add monitored site ownership

Revision ID: 41e7ef644594
Revises: b425b87e981b
Create Date: 2026-09-16 20:20:38.262729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41e7ef644594'
down_revision: Union[str, Sequence[str], None] = 'b425b87e981b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitored_sites', sa.Column('owner_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_monitored_sites_owner_id'), 'monitored_sites', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitored_sites_owner_id'), table_name='monitored_sites')
    op.drop_column('monitored_sites', 'owner_id')
    # ### end Alembic commands ###
