"""Add unique constraint for site issue fingerprints

Revision ID: b425b87e981b
Revises: 8d1d40f2731e
Create Date: 2026-09-16 15:40:25.101404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b425b87e981b'
down_revision: Union[str, Sequence[str], None] = '8d1d40f2731e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leak_issues") as batch_op:
        batch_op.create_unique_constraint(
            "uq_leak_issues_site_fingerprint",
            ["site_id", "fingerprint"],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leak_issues") as batch_op:
        batch_op.drop_constraint(
            "uq_leak_issues_site_fingerprint",
            type_="unique",
        )
    # ### end Alembic commands ###
